CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [UserName] NVARCHAR(50) NOT NULL UNIQUE,
    [Email] VARCHAR(256) NOT NULL UNIQUE, 
    [PasswordHash] VARCHAR(512) NULL
)

GO